export const ON_CHANGE_SEARCH_INPUT = "ON_CHANGE_SEARCH_INPUT";

export const CURRENT_USER_SUCCESS = "CURRENT_USER_SUCCESS";
export const CURRENT_USER_FAILED = "CURRENT_USER_FAILED";
export const REQUEST_BOX_SIZE_PENDING = "REQUEST_BOX_SIZE_PENDING";
export const REQUEST_BOX_SIZE_SUCCESS = "REQUEST_BOX_SIZE_SUCCESS";
export const REQUEST_BOX_SIZE_FAILED = "REQUEST_BOX_SIZE_FAILED";

export const LOAD_CURRENT_USER = "LOAD_CURRENT_USER";
export const CURRENT_ROUTE = "CURRENT_ROUTE";

export const REQUEST_SIGNIN_PENDING = "REQUEST_SIGNIN_PENDING";
export const REQUEST_SIGNIN_SUCCESS = "REQUEST_SIGNIN_SUCCESS";
export const REQUEST_SIGNIN_FAILD = "REQUEST_SIGNIN_FAILD";

export const ASSIGN_EMAIL = "ASSIGN_EMAIL";
export const ASSIGN_PASSWORD = "ASSIGN_PASSWORD";
export const REMOVE_VALIDATOR_FROM_STATE = "REMOVE_VALIDATOR_FROM_STATE";

export const REGISTER_EMAIL = "REGISTER_EMAIL";
export const REGISTER_PASSOWRD = "REGISTER_PASSOWRD";
export const REGISTER_NAME = "REGISTER_NAME";
export const REQUEST_REGISTER_PENDING = "REQUEST_REGISTER_PENDING";
export const REQUEST_REGISTER_SUCCESS = "REQUEST_REGISTER_SUCCESS";
export const REQUEST_REGISTER_FAILED = "REQUEST_REGISTER_FAILED";
